DefaultContentLanguage = "en"
baseURL = "https://hieuvo181.netlify.com/"
disqusShortname = "bilberry-hugo-theme"
enableRobotsTXT = true
googleAnalytics = ""
theme = "bilberry-hugo-theme"
title = "Hieu Vo Blog"
[Languages.de]
subtitle = "Hallo Welt! Dies ist der epischste Untertitel aller Zeiten."
title = "Mein cooler neuer Blog"
weight = 2
[Languages.en]
weight = 1
[blackfriday]
hrefTargetBlank = false
[outputs]
home = ["HTML", "JSON", "RSS"]
page = ["HTML"]
[params]
algolia_apiKey = "50ea7f8c41c0ad233926e0be2b769ed1"
algolia_appId = "Y2C4RWMPXW"
algolia_currentLanguageOnly = true
algolia_indexName = "default-content"
algolia_search = true
amountCategoriesInFooter = 7
amountLatestPostsInFooter = 7
author = "Lednerb"
copyrightBy = "by Lednerb"
copyrightUrl = "https://github.com/Lednerb"
copyrightUseCurrentYear = false
copyrightYearOverride = "2017"
creditsText = "Bilberry Hugo Theme"
creditsUrl = "https://github.com/Lednerb/bilberry-hugo-theme"
css_modules = []
customImage = ""
dateFormat = "2006-01-02"
description = "Bilberry Premium Theme for Hugo."
enableMomentJs = true
enable_mathjax = false
gravatarEMail = "code@lednerb.de"
js_modules = []
keywords = "blog,personal,responsive,search,font awesome,pages,posts,multilingual,highlight.js,syntax highlighting,premium,shortcuts"
overlayIcon = "fa-home"
paginate = 7
permanentTopNav = false
resizeImages = true
showFooter = true
showFooterLanguageChooser = true
showHeaderLanguageChooser = true
showReadingTime = false
showSocialMedia = true
stickyNav = false
subtitle = "Hello World! This is the most epic subtitle ever."
[[params.socialMediaLinks]]
icon = "fab fa-twitter"
link = "https://twitter.com/TheRealLednerb"
[[params.socialMediaLinks]]
icon = "fab fa-github"
link = "https://github.com/Lednerb"
[taxonomies]
author = "author"
category = "categories"
tag = "tags"
